name: firebase_authentication
description: Firebase auth package.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.5
  firebase_auth: ^3.10.0
  google_sign_in: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

